# Generated by Django 3.0 on 2019-12-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191227_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Ted Carlson', max_length=255),
            preserve_default=False,
        ),
    ]
