# Generated by Django 3.0 on 2019-12-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Opinion', max_length=255),
            preserve_default=False,
        ),
    ]
