# Generated by Django 3.0 on 2020-01-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
